name: Build release binary

on:
  push:
    tags:
      - release*
  workflow_dispatch:

jobs:
  build-sbf:
    runs-on: ubuntu-latest
    steps:
      - uses: hecrj/setup-rust-action@v2
        with:
          rust-version: stable
      - uses: actions/checkout@master
      - name: install solana
        run: sh -c "$(curl -sSfL https://release.solana.com/v1.17.0/install)"
      - name: Add to PATH
        shell: bash
        run: |
          echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
      - name: build sbf
        run: cargo build-sbf --manifest-path=./contract/Cargo.toml --sbf-out-dir=dist/contract
      - uses: actions/upload-artifact@v3
        with:
          name: target
          path: |
            dist/contract/contract.so

  build-binary:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            suffix: linux
          # - os: windows-latest
          #   suffix: win
          - os: macOS-latest
            suffix: osx

    steps:
      - uses: hecrj/setup-rust-action@v2
        with:
          rust-version: stable
      - uses: actions/checkout@master
      - name: build binary
        run: cargo build --release
      - name: rename binary file
        run: |
          ls target/release/
          mv target/release/server target/release/server-${{ matrix.suffix}}
          mv target/release/operator target/release/operator-${{ matrix.suffix}}

      - uses: actions/upload-artifact@v3
        with:
          name: target
          path: |
            target/release/server-${{ matrix.suffix}}
            target/release/operator-${{ matrix.suffix}}

  upload-release:
    permissions:
      contents: write
    needs:
      - build-binary
      - build-sbf

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: target
          path: target

      - run: ls -al target && ls -R target/ && file target/
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/*
            LICENSE
            README.md
