name: Build release binary

on: 
  push:
    tags:
      - release*
  workflow_dispatch: 

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            suffix: linux
          - os: windows-latest
            suffix: win
          - os: macOS-latest
            suffix: osx

    steps:
    - uses: hecrj/setup-rust-action@v2
      with:
        rust-version: stable
    - uses: actions/checkout@master
    - name: build binary
      run: cargo build --release
    - name: rename binary file 
      run: |
        ls target/release/
        mv target/release/server target/release/server-${{ matrix.suffix}}
        mv target/release/operator target/release/operator-${{ matrix.suffix}}
    
    - uses: actions/upload-artifact@v3
      with:
        name: target
        path: |
          target/server-${{ matrix.suffix}} target/release/server-${{ matrix.suffix}}
          target/operator-${{ matrix.suffix}} target/release/operator-${{ matrix.suffix}}